name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qtltsver: ['5.15.2', '6.2.4']

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qtltsver }}
      
    - name: MSVC Environment Setup
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure Build
      shell: bash
      run: |
        if [[ -n "${Qt5_DIR}" ]]; then export CMAKE_PREFIX_PATH=${Qt5_DIR}; fi
        if [[ -n "${Qt6_DIR}" ]]; then export CMAKE_PREFIX_PATH=${Qt6_DIR}; fi
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DOTPLIB_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build build --config Release

    - name: Run Unit Tests
      continue-on-error: true
      run: ctest --test-dir build --build-config Release --output-on-failure --output-junit tests.xml -V

    - name: Publish Unit Test Results (Linux)
      if: runner.os == 'Linux'
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: "results_${{ matrix.os }}_Qt${{ matrix.qtltsver }}"
        files:  "build/tests.xml"
        
    - name: Publish Unit Test Results (Windows/macOS)
      if: runner.os == 'Windows' || runner.os == 'macOS'
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      with:
        check_name: "results_${{ matrix.os }}_Qt${{ matrix.qtltsver }}"
        files:  "build/tests.xml"

  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Doxygen and Dependencies
        shell: bash
        run: sudo apt-get install doxygen graphviz -y

      - name: Run doxygen
        shell: bash
        run: ./scripts/generate_docygen.sh